"""create trabajos table

Revision ID: 5a4f626dca49
Revises: 
Create Date: 2025-11-08 22:24:00.023479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4f626dca49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajos',
    sa.Column('NumeroRegistro', sa.Integer(), nullable=False),
    sa.Column('CompaniaSeguro', sa.String(length=100), nullable=False),
    sa.Column('Anio', sa.Integer(), nullable=True),
    sa.Column('Mes', sa.Integer(), nullable=True),
    sa.Column('CantidadServicios', sa.Integer(), nullable=True),
    sa.Column('Region', sa.String(length=100), nullable=False),
    sa.Column('ValorPorServicio', sa.Float(), nullable=True),
    sa.Column('PorcentajeCobertura', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('NumeroRegistro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajos')
    # ### end Alembic commands ###
